server:
  port: 8084

spring:
  application:
    name: request-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
